# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

before_install:
 - sudo apt-get install libnlopt-dev

os:
 - linux

r:
 - oldrel
 - release
 - devel


cran: http://cran.rstudio.com
repos:
  CRAN: http://cran.rstudio.com

r_packages:
 - devtools

after_success:
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
