# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

os:
 - linux
 - osx

r:
 - oldrel
 - release
 - devel


cran: http://cran.rstudio.com
repos:
  CRAN: http://cran.rstudio.com

r_packages:
 - devtools
 - nloptr
