# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages

before_install:
 - sudo apt-get install libnlopt-dev


os:
 - linux
 - osx

r:
  - oldrel
  - release
  - devel
