# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

os:
 - linux
 - osx

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install libnlopt-dev
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install nloptr

r:
 - oldrel
 - release
 - devel


cran: http://cran.rstudio.com
repos:
  CRAN: http://cran.rstudio.com

r_packages:
 - devtools
# - nloptr
